version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

conda:
  environment: docs/environment.yml

# build:
#   tools:
#     python: "3.9"
#     # You can also specify other tool versions:
#     # nodejs: "16"
#     # rust: "1.55"
#     # golang: "1.17"