# generated by datamodel-codegen:
#   filename:  raw_metadata.json
#   timestamp: 2024-02-14T20:36:23+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class ALS832(BaseModel):
    metadata_type: str
    data_hierarchy_level: int
    pxY: int
    numslices: int
    pxX: int
    numrays: int
    pxZ: int
    num_angles: int
    pxsize: float
    px_size_units: str
    propagation_dist: float
    energy_float: float
    kev: float
    energy_str: str
    energy_units: str
    angularrange: float
    propagation_dist_units: str
    angles_deg: List[float]
    angles_rad: List[float]
